import Navigation from "./components/Navigation";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <div className="min-h-full">
          <Navigation>{children}</Navigation>
        </div>
      </body>
    </html>
  );
}
